### ISSUE TITLE
Commit analyzer doesn't detect breaking change

### ISSUE THREAD

**Issue by ruxandrafed** [semantic-release/commit-analyzer#100]
Hi, 

I have tried all ways of including the right keywords in my commit message to trigger a major release, but it keeps failing to detect it:

<img width="1113" alt="screen shot 2018-11-30 at 1 35 03 pm" src="https://user-images.githubusercontent.com/11021586/49316190-f65e7700-f4a4-11e8-9db0-01bac4e374d0.png">

I don't have any specific configuration, just using the default. So far, everything has worked as expected, except for trying to trigger a major release. 

Any thoughts?

**Comment by pvdlg** [comment]
Your commit is not formatted according to the [Angular convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines)

A breaking change should be identified by `BREAKING CHANGE:` in the footer of the commit, not `BREAKING CHANGES:`. See https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#footer


The example in the README is misleading though as it mention the angular preset by default support both `BREAKING CHANGE:` and `BREAKING CHANGES:` which used to be the case but not anymore apparently. That was changed a few month ago apparently: https://github.com/conventional-changelog/conventional-changelog/commit/03f0210e42dff58689ddf182694a8a6ca26e526b#diff-80a83b11bde68fe0ce9825d482a2c922L10

Fixed in #101

**Comment by ruxandrafed** [comment]
Thank you very much, @pvdlg! You were right. I have tried so many variations, just not this particular one. It seems it worked, much appreciated!
