### ISSUE TITLE
enable travis for all branches & disable for release tags

### ISSUE THREAD

**Issue by gr2m** [semantic-release/commit-analyzer#11]
Hey can you enable to run builds for all branches? When having commit access, we usually create branches and create a pull request from these

https://github.com/semantic-release/commit-analyzer/blob/91c125f2754bd433a309ee6eec12619ba520d10f/.travis.yml#L5-L7

But you can disable builds for the release tags by adding

```
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
```

**Comment by pvdlg** [comment]
It's already the case because Travis is configured to build the PR and the push.
Therefore:
- A push on a feature branch will build as soon there is a PR open (and rebuild on each push)
- A push on master will trigger a build
- A push on a greenkeeper branch will trigger a build even if there is no PR

The current config as the advantage of triggering only one build when you open a PR from a branch of the repo. With the one you propose it would trigger a PR build and a push build each time (which is not necessary, use Travis resources and delay the feedback from Travis)

See https://github.com/travis-ci/travis-ci/issues/1147

**Comment by gr2m** [comment]
Thanks for the explanation, that makes perfectly sense 👍

**Comment by gr2m** [comment]
actually let’s add this link as comment to the `.travis.yml` so others (including my future self) don’t ask themselves the same question :)
