### ISSUE TITLE
With preset conventionalcommits commits with ! are not recognized as a breaking change

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/commit-analyzer#153]
I think this case should be handled by the preset itself so I opened an issue over there: https://github.com/conventional-changelog/conventional-changelog/issues/543

If the `conventional-changelog` think it shouldn't be implemented over then we'll implement a workaround in `@semantic-release/commit-analyzer`.

**Comment by amannn** [comment]
@pvdlg Thanks so much for your help here, the commit analyzer now properly detects breaking changes!

However it seems like the fixes and features that are added with a breaking change can't be written to the changelog. Is it maybe due to the way these "!" commits are parsed?

I'm testing this in a repository and you can see an example here: https://github.com/amannn/semantic-release-test/compare/v3.0.0...v4.0.0. The major version was bumped correctly, but the "Bug Fixes" section of the changelog misses an entry from the first commit.

I'm now [updated the versions](https://github.com/amannn/semantic-release-test/compare/v6.0.1...v7.0.0) version of all [semantic plugins that are in use in the repo](https://github.com/amannn/semantic-release-test/blob/master/release.config.js).

Thanks again!

**Comment by pvdlg** [comment]
I think that's because you didn't configure the `conventionalcommits ` preset for `@semantic-release/release-notes-generator`: https://github.com/amannn/semantic-release-test/blob/386d265eafa56fd70b5cf93461a92cbb07bb3bd7/release.config.js#L4

If you want to make the config only once you can configure the `preset` directly at the top of the config object so it will be applied to both plugins.

**Comment by amannn** [comment]
Oh great, I didn't know that was possible. I didn't see it that the docs.

Anyhow, it [works great now](https://github.com/amannn/semantic-release-test/compare/v7.0.0...v8.0.0) – thank you for your help!
