### ISSUE TITLE
Add remaining Angular commit types to default release rules

### ISSUE THREAD

**Issue by amannn** [semantic-release/commit-analyzer#155]
From [the conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/):

> types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others.

Currently the release rules are based on a variety of conventions and a few examples from the Angular convention are used.

Would you be open to support the full range of Angular commit types, as it's also mentioned in the spec?

 - build
 - ci
 - docs
 - feat
 - fix
 - perf
 - refactor
 - style
 - test
 - revert

(from [Angular contributing guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type), plus the special "revert")

They are also mentioned in [conventional-commit-types](https://github.com/commitizen/conventional-commit-types/blob/master/index.json).

**Comment by pvdlg** [comment]
The missing types are not in the default release rules on purpose because they are not supposed to trigger a release.
We want to make a release only when that would result in a different package. If you make code formatting, CI scripts or unit test changes then there is no need to make a release as the package would be identical to the previous one.

**Comment by amannn** [comment]
Oh, I see – that makes sense to me. Thanks for explaining!

**Comment by jesuskata** [comment]
How can I add the rules to not hide in the CHANGELOG generated all the list of types? Because actually it just prints the types: fix, perf, and feat
