### ISSUE TITLE
The type field in the release rules doesn't seem to work if there is a space

### ISSUE THREAD

**Issue by vamsisunkara** [semantic-release/commit-analyzer#500]
We're using the angular preset and pretty much defaults everywhere else. I'm trying to add a release rule where a `breaking change` triggers a major release but it doesn't seem to be working. However, adding a rule for just `breaking` works just fine. I tried to add a rule for a very simple `a b` type and that doesn't work either.

I wanted to check if this is expected or if it is a bug. If this is expected behavior, it might be helpful to add a validation condition to inform developers that spaces are unsupported in the type of the commit.

I can provide any configuration snippets or logs that are needed to help troubleshoot.

**Comment by travi** [comment]
> I can provide any configuration snippets or logs that are needed to help troubleshoot.

please do. without an example, i don't understand your goal. the angular preset already supports including `BREAKING CHANGE: ` in the commit body to trigger a major release. would be best if you can provide a link to a public project

**Comment by vamsisunkara** [comment]
Yeah, the angular preset does support `BREAKING CHANGE: ` in the commit body/footer for major releases. However, the team finds the behavior to be inconsistent with other types such as `fix:` and `feat:` which release patch and minor versions respectively. 

I'm trying to get the same behavior for a major release (i.e. specify a prefix in the commit title resulting in a major release) as well. As such, I'm trying to configure semantic release to look for the `BREAKING CHANGE: ` prefix in the commit title and release a major version.

The problem is that, when there's a space in the commit type, I don't see a release happening.

Here are examples of my configuration -

### **Scenario 1:** `BREAKING CHANGE` commit type (doesn't release a major version when it should) ❌ 

configuration -

>     plugins: [
>         ['@semantic-release/commit-analyzer', {
>             "releaseRules": [{
>                 "type": "BREAKING CHANGE",
>                 "release": "major"
>             }]
>         }],
> 

        
commit message - `BREAKING CHANGE: updated readme`
        
result -

> [7:11:54 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
> [7:11:54 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: BREAKING CHANGE: updated readme
>   semantic-release:commit-analyzer Analyzing with custom rules +0ms
>   semantic-release:commit-analyzer Analyzing with default rules +1ms
> [7:11:54 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release

### **Scenario 2** : `breaking` commit type (correctly releases a major version) ✅ 

configuration -

>     plugins: [
>         ['@semantic-release/commit-analyzer', {
>             "releaseRules": [{
>                 "type": "breaking",
>                 "release": "major"
>             }]
>         }],

        
commit message - `breaking: Updated readme for a second time`

result - 

> [7:19:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: breaking: Updated readme for a second time
>   semantic-release:commit-analyzer Analyzing with custom rules +0ms
>   semantic-release:commit-analyzer The rule { type: 'breaking', release: 'major' } match commit with release type 'major' +0ms
>   semantic-release:commit-analyzer Release type 'major' is the highest possible. Stop analysis. +0ms
> [7:19:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major

### **Scenario 3** : `a b` commit type (does not create a major release when it should) ❌

This isn't something that would be used in a real environment. I used it to show that when the commit type has a space, the parser doesn't seem to work correctly.

configuration -

>     plugins: [
>         ['@semantic-release/commit-analyzer', {
>             "releaseRules": [{
>                 "type": "a b",
>                 "release": "major"
>             }]
>         }],

commit message -  `a b: updating README a third time`

result - 

> [7:28:08 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
> [7:28:08 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: a b: updating README a third time
>   semantic-release:commit-analyzer Analyzing with custom rules +0ms
>   semantic-release:commit-analyzer Analyzing with default rules +0ms
> [7:28:08 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release

Hopefully this clears things up, let me know if you want more logs/config to troubleshoot the problem. Appreciate the help!

**Comment by travi** [comment]
i think there are two parts to the situation here:
* should breaking changes be described as the "type" of the commit?
* should types be able to have spaces?

i think both of these questions boil down to understanding what the commit-type is for. the type describes what the change _is_, not how it should be release. `fix` specifically isnt `patch` because the change being described _is_ a bug fix. `feat` specifically isnt `minor` because the change being described _is_ a new feature. when committing the change, the goal is to describe the change without needing to think about how to release it. mapping what it is to how it is released is the responsibility of semantic-release.

the `BREAKING CHANGE: ` footer comes into play to provide additional context about how the described change impacts consumers. _any_ commit type (or what the change _is_) could break consumers. depending on the scale of a refactor, even a `refactor` commit might be breaking to consumers, even though the `refactor` type wouldnt result in a release on its own. the additional context provided by this footer enables semantic-release to take multiple bits of information describing what the change _is_ and translate it into an appropriate level release.

you can certainly choose to disagree with that context, but my hope is that it can be helpful in understanding how the semantic-release tool works and why. type describes what the change _is_, not the release level. breaking-change describes outcome of the change, not what it is, so our official recommendation is that breaking-change should not be described in the type.

if you do choose to go down a path that doesnt align with that model, i have to answer the second question with no, types should not have spaces. there are no standard conventions that use spaces for types. many of the standard conventions even shorten the intended words to enable commit subjects to stay short overall, even when providing multiple bits of valuable description in that first line. there are several options like `breaking`, `breakage`, or even just `break` that you could use that align with the goal of keeping types short.

**Comment by vamsisunkara** [comment]
Thank you for the additional context, I largely agree with most of what you said. I'm already using `breaking` in a couple of places and I have no problem with it. I thought this might be a bug which is why I reported it.  I don't think it is a good use of yours or my time to talk semantics (pun not intended). 

IMO, it would be useful for developers if the plugin validated that the commit type field does not contain spaces ([looks like the code is already doing that for other conditions](https://github.com/semantic-release/commit-analyzer/blob/master/lib/load-release-rules.js#L34-L41)). 

I got what I need from this conversation, so thank you.
