### ISSUE TITLE
"Fix: " prefix dominates over "feat: " one if latter used as a second line in commit message

### ISSUE THREAD

**Issue by hiaik** [semantic-release/commit-analyzer#508]
@semantic-release/commit-analyzer@9.0.2

Commit message is (multilines separated with `\n`):
```
fix: Merge branch 'DEVX-199-test4' into 'develop'
feat: Resolve DEVX-199 "Test4"
````

Expected behaviour that minor release (feat) will be chosen (not patch - fix).

Current behaviour: patch release is chosen (output below).

Output:
```
[1:49:44 AM] [semantic-release] › ℹ  Found 2 commits since last release
72[1:49:44 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
73[1:49:44 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: Merge branch 'DEVX-199-test4' into 'develop'
74feat: Resolve DEVX-199 "Test4"
75[1:49:44 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
76[1:49:44 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: Squash commits for branch 'DEVX-199-test4'
77feat: Resolve DEVX-199 "Test4"
78[1:49:44 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
79[1:49:44 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
```

**Comment by travi** [comment]
> Expected behaviour that minor release (feat) will be chosen (not patch - fix).

I don't understand how this would be expected behavior. semantic-release analyzes commits based on the chosen convention, which does not expect multiple commit subjects. Can you point to any docs that would suggest that this would work as you describe?

**Comment by hiaik** [comment]
Thanks @travi , I was looking at https://github.com/semantic-release/commit-analyzer#multiple-commits and did not find any limitations for multiline commits (thought it just should work).

Could you please share the doc link which I must have been missed?

Our use case is from GitLab
https://docs.gitlab.com/ee/user/project/merge_requests/commit_templates.html#default-template-for-merge-commits

it supports multiline commits which I thought will be supported by `semantic-release / commit-analyzer` to choose the higher prefix from all the lines provided within the commit.

**Comment by travi** [comment]
> I was looking at [semantic-release/commit-analyzer#multiple-commits](https://github.com/semantic-release/commit-analyzer#multiple-commits) and did not find any limitations for multiline commits (thought it just should work).

as covered in this link, the behavior you describe works across multiple individual commits, but not multiple commit headers in a single commit.

> it supports multiline commits which I thought will be supported by `semantic-release / commit-analyzer` to choose the higher prefix from all the lines provided within the commit.

multiline commits are supported by semantic-release, but according to the expectations of the chosen commit convention (angular by default). 

> Could you please share the doc link which I must have been missed?

for example, the [message format expected by the angular convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#commit-message-format) expects a header and optionally a body and footer. other possible conventions are listed for the preset option for the [commit-analyzer plugin](https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#options) and the [release-notes-generator plugin](https://github.com/semantic-release/release-notes-generator#options).

**Comment by hiaik** [comment]
Thanks @travi for details and explanation. Closing this one (misunderstood docs).

**Comment by hiaik** [comment]
Hi @travi 

Interesting case came up recently that for `BREAKING CHANGE:` prefix, we would have a different behaviour.

For the multiline commit message:
```
fix: Merge branch 'DEVX-261-breaking-change-test-1' into 'develop'
BREAKING CHANGE: [DEVX-261] test
Closes DEVX-261
See merge request viator/engineering/devx-pipeline-generator-test![74]
```

we will get `BREAKING CHANGE:` respected from the second line of the commit.
And major release is trigerred.
```
[4:35:01 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[4:35:01 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: Merge branch 'DEVX-261-breaking-change-test-1' into 'develop'
BREAKING CHANGE: [DEVX-261] test
Closes DEVX-261
See merge request viator/engineering/devx-pipeline-generator-test![74](https://gitlab.dev.tripadvisor.com/viator/engineering/devx-pipeline-generator-test/-/jobs/8851114#L74)
[4:35:01 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
[4:35:01 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: major release
```

Docs example https://github.com/semantic-release/semantic-release#commit-message-format

It is kind of inconsistent behaviour to me that:
- `BREAKING CHANGE:` should be in the footer (like 2nd line of multiline commit message)
- but if `feat: ` will be on 2nd line, it will be ignored

Do you know the reason of special treatment for `BREAKING CHANGE:` ?

Thanks in advance.

**Comment by travi** [comment]
@hiaik please do not ping maintainers directly for support questions.

> It is kind of inconsistent behaviour to me that:
>
> BREAKING CHANGE: should be in the footer (like 2nd line of multiline commit message)
but if feat:  will be on 2nd line, it will be ignored

keep in mind that semantic-release does not define the details of the commit convention defined by your chosen conventional-changelog preset. we default to the angular preset, but you can choose a different conventional-changelog preset (that is also not defined by us) or even create your own custom convention preset. i highlight this point because the answer to the root of your question is that this is how the underlying angular convention for the default preset (and the conventional-commits convention) is defined. you should read the [details of the underlying convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#commit-message-format) to better understand its expectations. 

> Do you know the reason of special treatment for BREAKING CHANGE: ?

since the _why_ might be unclear from the convention documentation, it is because the commit _type_ is intended to describe what the change _is_ (new feature, bug fix, refactor, etc), not necessarily the impact of the change from the perspective of the user. while commit _types_ are sometimes enough information for a tool like semantic-release to determine the impact to the consumer, and therefore the level of version bump to increment, `BREAKING CHANGE: ` provides supplementary information for determining consumer impact. if the commit _type_ was defined as breaking or similar, the information about what the change _is_ would be lost. any commit type, even a `refactor` can be breaking from the perspective of the consumer of the package if the scope of the refactor goes beyond that package.

**Comment by seebeen** [comment]
@hiaik I think you're misunderstanding the flow, and the commit message type.

Let's break it down:
* Semantic release does work for multiple commits
* Highest release type is always honored.

Let's assume you're making a PR with 3 commits
fix(component): Fixes this  
feat: Added feat  
fix: Fixed curl not working on linux
BREAKING CHANGE: Requires openssl v3.1.3

commit-analyizer would go over commits and do the following
-> increment patch  
-> increment minor
-> increment minor -> increment major (breaking change found)  

Any commit type can introduce breaking change, and by default each breaking change increments major version (unless you personally set it up differently).

If the commit type warrants a new release, **commit with the highest release type will determine the global release type**.

If you would like to limit the major version incrementing to the specific commit type you can configure your `releaseRules` as you see fit.
Otherwise - plugin is working as intended :)
