### ISSUE TITLE
How to pin the commit-analyzer version 

### ISSUE THREAD

**Issue by julioagos** [semantic-release/commit-analyzer#516]
Any guidance on how to pin the exact version of commit-analyzer. Here is our releaserc file. 
 
```
{
    "branches": ["master",{"name": "develop", "prerelease": true}],
    "debug": "true",
    "plugins": [
      ["@semantic-release/commit-analyzer", {
      "preset": "conventionalcommits"
        }],   
      "@semantic-release/release-notes-generator",
      "@semantic-release/github"
     ]
  }
```

**Comment by travi** [comment]
managing versions depends on how you install them. if using based on it being a dependency of semantic-release, you are already using a version that our team has proven to be compatible. if installing separately, you can either set the version in your package.json or by appending `@x.x.x` after the dependency in your installation command. 

if you are experiencing version problems since the weekend, the commit-analyzer is unlikely to be your problem, but instead your installation of the conventionalcommits preset. i would focus your efforts on pinning that to the version before the major version that was released this weekend with breaking changes.

**Comment by travi** [comment]
likely related to https://github.com/semantic-release/semantic-release/issues/2922

**Comment by deantchi** [comment]
@julioagos 
you can try:
```
{
    "branches": ["master",{"name": "develop", "prerelease": true}],
    "debug": "true",
    "plugins": [
      ["@semantic-release/commit-analyzer": "v9.0.2", {
      "preset": "conventionalcommits"
        }],   
      "@semantic-release/release-notes-generator",
      "@semantic-release/github"
     ]
  }
```

**Comment by travi** [comment]
> @julioagos 
> you can try:
> ```
> {
>     "branches": ["master",{"name": "develop", "prerelease": true}],
>     "debug": "true",
>     "plugins": [
>       ["@semantic-release/commit-analyzer": "v9.0.2", {
>       "preset": "conventionalcommits"
>         }],   
>       "@semantic-release/release-notes-generator",
>       "@semantic-release/github"
>      ]
>   }
> ```

This is not how the config files work. It is not appropriate to include a version number there

**Comment by julioagos** [comment]
> managing versions depends on how you install them. if using based on it being a dependency of semantic-release, you are already using a version that our team has proven to be compatible. if installing separately, you can either set the version in your package.json or by appending `@x.x.x` after the dependency in your installation command.
> 
> if you are experiencing version problems since the weekend, the commit-analyzer is unlikely to be your problem, but instead your installation of the conventionalcommits preset. i would focus your efforts on pinning that to the version before the major version that was released this weekend with breaking changes.

Thanks for the help. the conventionalcommits preset was what was broken. I pinned the version and it is working again
