### ISSUE TITLE
deps changes do not trigger release

### ISSUE THREAD

**Issue by tisonkun** [semantic-release/commit-analyzer#536]
Source code -

https://github.com/semantic-release/commit-analyzer/blob/7055003c9c818a8a4504cf2c2a40892556be6f3e/lib/default-release-rules.js#L30

Unexpected workflow run -

https://github.com/korandoru/setup-zig/actions/runs/6368966403/job/17288770353

Since it contains a `build(deps): ...` commit, I expected the run should trigger a patch release.

**Comment by travi** [comment]
it appears that you are using the default preset for semantic-release (angular). therefore, the `component` property of the express convention does not apply. also, updating a github action for your project should not result in any notable changes for your consumers, so not releasing for that update would follow our recommendation. dependabot will normally use the `fix` commit type for production dependencies, which would result in a release using the angular preset.

**Comment by tisonkun** [comment]
@travi Thanks for your explanation!

It's interesting that the code snippet above from `default-release-rules.js` doesn't have a preset field but we actually use its items differently based on the preset enabled. Could you guide me where the related source code?

**Comment by tisonkun** [comment]
> dependabot will normally use the fix commit type for production dependencies

The dependabot use `build(deps)` - https://github.com/korandoru/setup-zig/pull/126

**Comment by travi** [comment]
> The dependabot use `build(deps)` - [korandoru/setup-zig#126](https://github.com/korandoru/setup-zig/pull/126)

i primarily use renovate rather than dependabot, so my memory of the dependabot defaults is not perfect. it looks like you need to explicitly configure this behavior for dependabot [using `prefix` and `prefix-development`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)

**Comment by travi** [comment]
> It's interesting that the code snippet above from `default-release-rules.js` doesn't have a preset field but we actually use its items differently based on the preset enabled

commits are evaluated by the commit-analyzer based on the [chosen preset](https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#options). the angular preset does not populate `component`, so the comparison to those `component` options will never match in that case.

**Comment by travi** [comment]
i'm going to go ahead and close this issue because the commit-analyzer is working as expected. if you have further configuration questions around the commit-convention presets, please [open a discussion](https://github.com/semantic-release/semantic-release/discussions/categories/commit-convention) instead.

**Comment by tisonkun** [comment]
Thank you!
