### ISSUE TITLE
Handle commits of type "revert"

### ISSUE THREAD

**Issue by f0rr0** [semantic-release/commit-analyzer#84]
Given commits: A -> B -> C -> D -> HEAD

I did: 
```
$ git revert --no-commit D
$ git revert --no-commit C
$ git revert --no-commit B
$ git commit -m "revert(something): restore some other thing"
```

semantic-release skipped a new release for this commit.

Is this expected behaviour? What is the correct way to revert commits and make a new release?

**Comment by pvdlg** [comment]
If you have a revert commit and the reverted commit within the same release (i.e. between the last release and HEAD) semantic-release will ignore both because as they cancel each other they don't change the code therefore doesn't require a release.

If you have a revert commit without the commit it revert in the release than semantic-release will do a `patch` release.

See https://github.com/semantic-release/commit-analyzer/pull/78#issue-199923567

See https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-revert-a-release

**Comment by pvdlg** [comment]
Closing as I imagine the previous comment answered your question.

**Comment by guillaumearm** [comment]
Here I'm having the issue with a prelease branch, is it intended ?

1. I push a feat: something on my prerelease branch -> it make a pre-release
2. I push a revert commit -> it does not make the pre-release

Am I missing something ?
Should I create a separate issue for this ?

thanks for your help.
